apiVersion: v1
description: Bookinfo Details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student12/details
maintainers:
  - name: student12
    email: devop012@mail.kmutt.ac.th
sources:
  - https://github.com/i3lackash/bookinfo-details